[book]
authors = ["Gabriel Malosto"]
description = "Guia de configuração de ambiente de desenvolvimento."
language = "pt-br"
multilingual = false
src = "src"
text-direction = "ltr"
title = "Ambiente de desenvolvimento"

[rust]
edition = "2021"

[build]
build-dir = "book"
create-missing = false
use-default-preprocessors = true

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
smart-punctuation = true
git-repository-url = "https://github.com/gabdumal/book_dev_env"
site-url = "/book_dev_env/"
additional-css = ["src/styles.css"]

[output.markdown]
