[book]
authors = ["Gabriel Malosto"]
description = "Guia de configuração de ambiente de desenvolvimento em C e C++, utilizando Clang, LLDB, CMake e VsCode."
language = "pt-br"
multilingual = false
src = "src"
text-direction = "ltr"
title = "Ambiente de desenvolvimento em C e C++, com CMake e VsCode"


[rust]
edition = "2021"

[build]
build-dir = "book"
create-missing = true
use-default-preprocessors = true

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
smart-punctuation = true
git-repository-url = "https://github.com/gabdumal/book_c_cpp_env"
site-url = "/book_c_cpp_env/"

[output.markdown]
